---
layout: reference
section: learn
title: FromException
permalink: /learn/ref/Microsoft.Coyote.Tasks/Task/FromException
---
# Task.FromException method (1 of 2)

Creates a [`Task`](../TaskType) that is completed with a specified exception.

```csharp
public static Task FromException(Exception exception)
```

| parameter | description |
| --- | --- |
| exception | The exception with which to complete the task. |

## Return Value

The faulted task.

## See Also

* class [Task](../TaskType)
* namespace [Microsoft.Coyote.Tasks](../TaskType)
* assembly [Microsoft.Coyote](../../MicrosoftCoyoteAssembly)

---

# Task.FromException&lt;TResult&gt; method (2 of 2)

Creates a [`Task`](../Task-1Type) that is completed with a specified exception.

```csharp
public static Task<TResult> FromException<TResult>(Exception exception)
```

| parameter | description |
| --- | --- |
| TResult | The type of the result returned by the task. |
| exception | The exception with which to complete the task. |

## Return Value

The faulted task.

## See Also

* class [Task&lt;TResult&gt;](../Task-1Type)
* class [Task](../TaskType)
* namespace [Microsoft.Coyote.Tasks](../TaskType)
* assembly [Microsoft.Coyote](../../MicrosoftCoyoteAssembly)

<!-- DO NOT EDIT: generated by xmldocmd for Microsoft.Coyote.dll -->
